version: '1'

services:
  # PostgreSQL Private Service (Bypasses Render's 1-free-database limit)
  - type: pserv
    name: vault-postgres
    runtime: image
    image: docker.io/library/postgres:15-alpine
    plan: free
    envVars:
      - key: POSTGRES_DB
        value: vaultdb
      - key: POSTGRES_USER
        value: vaultuser
      - key: POSTGRES_PASSWORD
        value: vaultpassword

  # Redis Private Service (Free tier)
  - type: pserv
    name: vault-redis
    runtime: image
    image: docker.io/library/redis:7-alpine
    plan: free

  # MongoDB Private Service (Free tier)
  - type: pserv
    name: vault-mongodb
    runtime: image
    image: docker.io/library/mongo:6
    plan: free

  # Java Spring Boot Backend Web Service
  - type: web
    name: vault-backend
    runtime: docker
    plan: free
    envVars:
      - key: SERVER_SSL_ENABLED
        value: "false"
      - key: PORT
        value: "8080"
      - key: DB_URL
        value: jdbc:postgresql://vault-postgres:5432/vaultdb
      - key: DB_USER
        value: vaultuser
      - key: DB_PASSWORD
        value: vaultpassword
      - key: REDIS_HOST
        value: vault-redis
      - key: REDIS_PORT
        value: "6379"
      - key: MONGO_URI
        value: mongodb://vault-mongodb:27017/vault_audit?directConnection=true
      - key: JWT_SECRET
        generateValue: true
      - key: AES_SECRET_KEY
        value: "SuperSecretVaultKeyEncryptAtRest12"
      - key: CORS_ALLOWED_ORIGINS
        value: "http://localhost:5173" # Update this in Render dashboard settings with Vercel frontend URL once deployed
